NDefines.NGame.START_DATE = "1900.1.1.1"
NDefines.NGame.END_DATE = "2030.1.1.1"
NDefines.NGraphics.MINIMUM_PROVINCE_SIZE_IN_PIXELS = 2			-- Vanilla is 8, just to make the game stop complaining

NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 1000					-- increased all max air stats tenfold.
NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 1000
NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 8000
NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 1000

NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 24			-- how many divisions a corps commander is limited to. 0 = inf, < 0 = blocked
NDefines.NMilitary.CORPS_COMMANDER_ARMIES_CAP = -1				-- how many armies a corps commander is limited to. 0 = inf, < 0 = blocked
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 30				-- how many divisions a field marshall is limited to. 0 = inf, < 0 = blocked
NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 5					-- how many armies a field marshall is limited to. 0 = inf, < 0 = blocked

NDefines.NCountry.POLITICAL_POWER_LOWER_CAP = -500.0			-- Min amount of political power country should have
NDefines.NCountry.POLITICAL_POWER_UPPER_CAP = 5000.0			-- Max amount of political power country should have
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 2500
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 2500
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 2500

NDefines.NDiplomacy.TENSION_STATE_VALUE = 1.5
NDefines.NDiplomacy.TENSION_ANNEX_NO_CLAIM = 1.5		-- Amount of tension generated by annexing a state you don't have claims on
NDefines.NDiplomacy.TENSION_ANNEX_CLAIM = 0.5			-- Amount of tension generated by annexing a state you DO have claims on
NDefines.NDiplomacy.TENSION_ANNEX_CORE = 0.3			-- Amount of tension generated by annexing a state that is your core